SELECT * FROM MEMBERTBL;
SELECT * FROM MEMBERTBL
WHERE MEMBERNAME = '°í¾çÀÌ';

SELECT PRODUCTNAME, PRICE, AMOUNT FROM PRODUCTTBL;

CREATE TABLE "my testTBL" (id NUMBER(4));
SELECT * FROM "my testTBL";
SELECT * FROM my testTBL;

DROP TABLE "my testTBL";
commit;